### PR TITLE
build: bump gradle 6.9.2 -> 8.2.1

### PR DESCRIPTION
**Pull request by jdrueckert**
Relates to https://github.com/MovingBlocks/Terasology/pull/5109
Relates to https://github.com/MovingBlocks/Terasology/pull/4653

### Contains

* Updating gradle from 6.9.2 -> 8.2.1
* Updating gradle's files which became invalid

### How to test

1. Go into your Terasology workspace
2. Run `groovyw lib get CrashReporter`
3. In `libs/CrashReporter` check out this branch
4. Start Terasology and provoke a crash (e.g. by checking out commit 97f180b1513151ee787d2b0d78cad5c1fc861a2c in the engine repo)
5. Check that CrashReporter opens and works fine

### Remarks

Java 20 is not yet supported, see https://github.com/gradle/gradle/issues/23488.

### CODE REVIEW

**Comment by jdrueckert** [comment]
Checks are failing, but it looks like they were failing before...?

**Comment by BenjaminAmos** [comment]
Is this possibly related to the failing test? It appears to try and fetch a client certificate to authenticate against the drive API with.
https://github.com/MovingBlocks/CrashReporter/blob/9d169572776c9e882df3e061c66393e3368b6c24/cr-core/src/main/java/org/terasology/crashreporter/logic/GoogleDriveConnector.java#L179-L191

`jenkins.terasology.io` hasn't been up for a while now.

**Comment by jdrueckert** [comment]
Good find @BenjaminAmos !
I asked @Cervator on Discord, whether they `gooey-drive-*.p12` is available on the (in-between) jenkins setup we're currently using.

**Comment by Cervator** [comment]
Temp Jenkins is pretty basic and I did not cover much stuff that seemed secondary or tertiary - I wasn't even sure if that file was in use still, I did spot it just the other day when going through the InfraPlayground repo wondering what's needed and what to even automate.

I'm not even sure what it makes sense to let the CR support - the few times we got a (working) use of the GDrive integration it was awkward vs pastebin since you had to go download a file, extract, and view logs locally. It may make more sense to retire it and focus on pastebin

In any case there's a tiny readme section over at https://github.com/MovingBlocks/InfraPlayground/tree/master/jenkins/cbc#setup-google-drive-serviceaccount-key with the file living in the same directory.

Even though we don't use the CBC Jenkins now it doesn't look _too_ complex to sort out and port over, but the big question (to me) remains: should we?

**Comment by jdrueckert** [comment]
Just tested it via the engine repo and it tests out fine. But as I'm the author of this PR, I cannot approve it.

**Review by BenjaminAmos — APPROVED** [review]

**Pull request merged**
